algoritmo "ex1"
// Função : Faça um algoritmo que receba dois números Este comando simplesmente limpa a tela DOS do Visualg (a simulação e exiba o resultado da sua soma.
// Seção de Declarações
var
   x, y: inteiro

inicio
   // Seção de Comandos
   escreval("Digite o primeiro número: ")
   leia(x)
   escreval("Digite o segundo número: ")
   leia(y)
   escreva("A soma dos números é: ",x+y)
fimalgoritmo
